name: build and deploy to gh-pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build_and_deploy_to_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@main
        with:
          node-version: 14

      - run: |
          npm install
          npm run build

      - run: echo 'zackdk.com' > build/CNAME

      - env:
          TOKEN: ${{secrets.TOKEN}}
        run: |
          cd build
          git init
          git config --local user.name zackdk
          git config --local user.email 958059970@qq.com
          git remote add origin https://$TOKEN@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy gh-pages"
          git push origin gh-pages -f
